Update simple-pipeline.yml

diff --git a/.github/workflows/simple-pipeline.yml b/.github/workflows/simple-pipeline.yml
--- a/.github/workflows/simple-pipeline.yml
+++ b/.github/workflows/simple-pipeline.yml
@@ -32,10 +32,31 @@ jobs:
           source venv/bin/activate
           pip install -r requirements.txt
 
-  # 2. Job: Validación del Pull Request (dependiente del job "build")
+  # 2. Job: Validación de comentario en el commit (depende de "build")
+  commit_validation:
+    runs-on: ubuntu-latest
+    needs: build  # Dependencia del job "build"
+
+    steps:
+      # Clona el repositorio
+      - name: 'Checkout code'
+        uses: actions/checkout@v4
+
+      # Verificar que el último commit tenga un comentario
+      - name: 'Check commit message'
+        run: |
+          commit_message=$(git log -1 --pretty=%B)
+          if [ -z "$commit_message" ]; then
+            echo "Error: El commit debe tener un comentario."
+            exit 1
+          else
+            echo "Commit válido con mensaje: $commit_message"
+          fi
+
+  # 3. Job: Validación del Pull Request (depende del job "commit_validation")
   validate_pr:
     runs-on: ubuntu-latest
-    needs: build  # Aquí se define la dependencia del job "build"
+    needs: commit_validation  # Dependencia del job "commit_validation"
 
     steps:
       # Clonar el repositorio
@@ -55,5 +76,5 @@ jobs:
             exit 1
           else
             echo "El Pull Request tiene un comentario válido."
-          fi
+
 
